# Generated by Django 4.2 on 2025-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetBoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
