# Generated by Django 4.2 on 2025-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetBoutiqueApp', '0003_arrepentimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrepentimiento',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='arrepentimiento',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
